# Copyright 2018 the stund authors
# Licensed under the MIT License

language: rust

cache: cargo

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      rust: stable
    - os: linux
      sudo: required
      dist: xenial
      rust: beta
    - os: linux
      sudo: required
      dist: xenial
      rust: nightly
    - os: osx
      rust: stable
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add rustfmt

script:
  - |
    cargo fmt --all -- --check &&
    cargo build --verbose &&
    cargo test
