[package]
name = "stund"
version = "0.1.0"
authors = ["Peter Williams <peter@newton.cx>"]

[workspace]

[dependencies]
atty = "0.2"
daemonize = "0.2"
failure = "0.1"
futures = "0.1"
libc = "0.2"
state_machine_future = "0.1"
structopt = "0.2"
stund_protocol = { path = "protocol", version = "0.1.0" }
tokio-borrow-stdio = { path = "tokio-borrow-stdio", version = "0.1.0" }
tokio-core = "0.1"
tokio-io = "0.1"
tokio-pty-process = { path = "tokio-pty-process", version = "0.1.0" }
tokio-serde-json = { git = "https://github.com/carllerche/tokio-serde-json" }
tokio-signal = "0.1"
tokio-uds = "0.1"
