[package]
name = "stund_protocol"
version = "0.1.0"
authors = ["Peter Williams <peter@newton.cx>"]

[dependencies]
failure = "0.1"
futures = "0.1"
libc = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
state_machine_future = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-serde-json = { git = "https://github.com/carllerche/tokio-serde-json" }
tokio-signal = "0.1"
tokio-uds = "0.1"

